events {}
http {
  server {
    listen 8000;
    client_max_body_size 50m;
    location / {
      proxy_pass http://api:8000;
      proxy_set_header Host $http_host;
      proxy_read_timeout 600s;
    }
  }
  server {
    listen 3000;
    client_max_body_size 50m;
    location / {
      proxy_pass http://frontend:3000;
      proxy_http_version 1.1;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Proto http;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_read_timeout 600s;
      add_header X-Insights-Local-Mode connected always;
    }
  }
}
